# 部署静态内容到GitHub Pages的简单工作流程
名称：将静态内容部署到Pages

在：
  # 在针对默认分支的推送触发# 在针对默认分支的推送触发
  推送推送：
    分支：["main"]

  # 允许您从 Actions 标签手动运行此工作流# 允许您从 Actions 标签手动运行此工作流
  工作流派送：

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  目录：阅读
  页数：写
  id令牌:   id-token: 写

# 仅允许一个并发部署，跳过在进行中的运行和最新排队之间的排队运行。
# 但是，请不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
并发性：
  组： "页面"
  取消正在进行中:   取消正在进行中: 否

工作：
  # 单个部署作业，因为我们只是进行部署
  部署:
    环境：
      名称： 名称: github-pages
      url:       url: ${{ steps.deployment.outputs.page_url }}{{ steps.deployment.outputs.page_url }}
    运行于：ubuntu-latest
    步骤：
      -       - 名称：结账
        用途：actions/checkout@v4
      -       - 名称：设置页面
        使用:         使用: actions/configure-pages@v5
      - name      - - name: 上传工件
        使用：actions/upload-pages-artifact@v3
        与：
          # 上传整个仓库
          路径: '.'
      - 名称: 部署到GitHub Pages
        id： 部署
        使用： actions/deploy-pages@v4
